"""add_real_estate_tables

Revision ID: 0fa6a8ea1e0d
Revises: f1c8c1e06add
Create Date: 2025-10-17 10:47:53.618709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0fa6a8ea1e0d'
down_revision: Union[str, Sequence[str], None] = 'f1c8c1e06add'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('amenities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('place_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('place_id')
    )
    op.create_index(op.f('ix_amenities_id'), 'amenities', ['id'], unique=False)
    op.create_index(op.f('ix_amenities_name'), 'amenities', ['name'], unique=False)
    op.create_table('demographics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('neighborhood', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('population', sa.Integer(), nullable=True),
    sa.Column('median_income', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('median_age', sa.Float(), nullable=True),
    sa.Column('education_levels', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_demographics_id'), 'demographics', ['id'], unique=False)
    op.create_index(op.f('ix_demographics_neighborhood'), 'demographics', ['neighborhood'], unique=True)
    op.create_table('properties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=True),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('property_type', sa.String(), nullable=True),
    sa.Column('year_built', sa.Integer(), nullable=True),
    sa.Column('lot_size_sqft', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_address'), 'properties', ['address'], unique=True)
    op.create_index(op.f('ix_properties_id'), 'properties', ['id'], unique=False)
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('school_district', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schools_id'), 'schools', ['id'], unique=False)
    op.create_index(op.f('ix_schools_name'), 'schools', ['name'], unique=False)
    op.create_table('transit_stops',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stop_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=False),
    sa.Column('lng', sa.Float(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('routes', sa.JSON(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stop_id')
    )
    op.create_index(op.f('ix_transit_stops_id'), 'transit_stops', ['id'], unique=False)
    op.create_index(op.f('ix_transit_stops_name'), 'transit_stops', ['name'], unique=False)
    op.create_table('zoning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('zone_code', sa.String(), nullable=False),
    sa.Column('zone_name', sa.String(), nullable=False),
    sa.Column('zone_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permitted_uses', sa.Text(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_zoning_id'), 'zoning', ['id'], unique=False)
    op.create_index(op.f('ix_zoning_zone_code'), 'zoning', ['zone_code'], unique=True)
    op.create_table('assessments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('assessed_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('land_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('improvement_value', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('assessment_year', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    op.create_index(op.f('ix_assessments_id'), 'assessments', ['id'], unique=False)
    op.create_table('chat_sessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('session_title', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_sessions_id'), 'chat_sessions', ['id'], unique=False)
    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('beds', sa.Integer(), nullable=True),
    sa.Column('baths', sa.Float(), nullable=True),
    sa.Column('area_sqft', sa.Integer(), nullable=True),
    sa.Column('property_img', sa.String(), nullable=True),
    sa.Column('listing_url', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('listed_date', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('property_id')
    )
    op.create_index(op.f('ix_listings_id'), 'listings', ['id'], unique=False)
    op.create_table('property_zoning',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('property_id', sa.Integer(), nullable=False),
    sa.Column('zone_code', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['property_id'], ['properties.id'], ),
    sa.ForeignKeyConstraint(['zone_code'], ['zoning.zone_code'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_zoning_id'), 'property_zoning', ['id'], unique=False)
    op.create_table('school_catchments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('school_id', sa.Integer(), nullable=False),
    sa.Column('catchment_name', sa.String(), nullable=False),
    sa.Column('boundary', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['school_id'], ['schools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_school_catchments_id'), 'school_catchments', ['id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('query_type', sa.String(), nullable=True),
    sa.Column('property_address', sa.String(), nullable=True),
    sa.Column('api_endpoint', sa.String(), nullable=True),
    sa.Column('response_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_id'), 'chat_messages', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chat_messages_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_school_catchments_id'), table_name='school_catchments')
    op.drop_table('school_catchments')
    op.drop_index(op.f('ix_property_zoning_id'), table_name='property_zoning')
    op.drop_table('property_zoning')
    op.drop_index(op.f('ix_listings_id'), table_name='listings')
    op.drop_table('listings')
    op.drop_index(op.f('ix_chat_sessions_id'), table_name='chat_sessions')
    op.drop_table('chat_sessions')
    op.drop_index(op.f('ix_assessments_id'), table_name='assessments')
    op.drop_table('assessments')
    op.drop_index(op.f('ix_zoning_zone_code'), table_name='zoning')
    op.drop_index(op.f('ix_zoning_id'), table_name='zoning')
    op.drop_table('zoning')
    op.drop_index(op.f('ix_transit_stops_name'), table_name='transit_stops')
    op.drop_index(op.f('ix_transit_stops_id'), table_name='transit_stops')
    op.drop_table('transit_stops')
    op.drop_index(op.f('ix_schools_name'), table_name='schools')
    op.drop_index(op.f('ix_schools_id'), table_name='schools')
    op.drop_table('schools')
    op.drop_index(op.f('ix_properties_id'), table_name='properties')
    op.drop_index(op.f('ix_properties_address'), table_name='properties')
    op.drop_table('properties')
    op.drop_index(op.f('ix_demographics_neighborhood'), table_name='demographics')
    op.drop_index(op.f('ix_demographics_id'), table_name='demographics')
    op.drop_table('demographics')
    op.drop_index(op.f('ix_amenities_name'), table_name='amenities')
    op.drop_index(op.f('ix_amenities_id'), table_name='amenities')
    op.drop_table('amenities')
    # ### end Alembic commands ###
